### ISSUE TITLE
Unable to process a Telegram group export

### ISSUE THREAD

**Issue by dimonier** [alexlyzhov/telegram-to-markdown#1]
Getting an error while running on a folder with the exported Telegram group:

  File "...\telegram-to-markdown\convert.py", line 112, in convert
    chats_list = data['chats']['list']
KeyError: 'chats'

The group was https://t.me/hlebosyr

**Clarification**: I tried to process an export done with the **Export chat history** command in the Telegram Desktop app.

**Comment by alexlyzhov** [comment]
I see. This code isn't really intended to work on any other chat than "Saved messages", unfortunately, so you'd have to tinker with it a bit to make it work.
